### ISSUE TITLE
Mobile-Home page: Pop up 'Select Language menu' is not centered. It flow out of the page container.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Starkeys#31]
1. Pop up menu is not working properly on devices.

![img_0697](https://cloud.githubusercontent.com/assets/13309730/10902145/acc5636a-821f-11e5-967d-294901063f14.PNG)

**Comment by mahender-sowedane** [comment]
Still Pop-up menu is not working properly on devices.

![img_0984](https://cloud.githubusercontent.com/assets/13309730/11137833/92c4ce00-89e1-11e5-9b09-3a761107433b.PNG)

**Comment by saif-titan** [comment]
discussed  with ricky
