### ISSUE TITLE
Contact us page - Mobile: When validating the fields it will destroy the alignment,  it's better to have it display in 1 column

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Starkeys#36]
1. Applicable for all languages.

![img_0709](https://cloud.githubusercontent.com/assets/13309730/10905921/840b41c8-8243-11e5-961f-3b54081a4001.PNG)

**Comment by saif-titan** [comment]
We can't make design for each language, Because each language has its own font widths and font faces.
