### ISSUE TITLE
Home - our products: Spacing between thumbnails is too different from the design.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Starkeys#61]
![image](https://cloud.githubusercontent.com/assets/11186313/11651254/6c7e875c-9dca-11e5-9811-83aa807d7387.png)

**Comment by Santosh-titan** [comment]
Yes, PSD design for home page category layout is not correct I already sent email to jolene regarding this issue. here is her response.
![email](https://cloud.githubusercontent.com/assets/13828562/11716207/289d699a-9f6e-11e5-9cc7-f52a7b818f1f.JPG)

**Comment by roseliesromeo** [comment]
We'll mark this one as won't fix since this is design error.
