### ISSUE TITLE
Sidebar: There is no active state applied for the category for the active product single page.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Starkeys#78]
![image](https://cloud.githubusercontent.com/assets/11186313/11677738/1b653570-9e7c-11e5-89f4-35c29822eed1.png)

**Comment by Santosh-titan** [comment]
Note: Some times same product available in two are more categories then all its categories will display in active position.
http://starkeyproducts.stage.titanweb.com.au/products/category-test/sub-category/a-variable-product/
