### ISSUE TITLE
Home - products section: Broken layout of the product thumbnails.  There is much gap between the category title and the first thumbnail while for the rest, the title is placed at the base of the image.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Starkeys#87]
S4 (portrait)
![image](https://cloud.githubusercontent.com/assets/11186313/11737231/3aabb944-a012-11e5-9faf-6eb6be7ec86e.png)

**Comment by Santosh-titan** [comment]
I think it is cache issue, Please clear your device browser cache. Its working fine in my devices.
![screenshot_2015-12-11-12-25-28](https://cloud.githubusercontent.com/assets/13828562/11737850/4f9583f8-a003-11e5-898b-0385e1217554.png)

**Comment by roseliesromeo** [comment]
We'll mark this as won't fix because the issue is reproducible in our end.
![image](https://cloud.githubusercontent.com/assets/11186313/11738133/e97ca03e-a01a-11e5-8d8d-239f8b046f28.png)
